/**
 * modules/component-search/kicadExport.ts
 * 真实 KiCad 格式文件生成 —— S-表达式文本格式，KiCad 7+ 可直接打开。
 * .kicad_mod：从 PAD_FOOTPRINTS 真实焊盘数据生成
 * .kicad_sym：从符号端口定义生成
 * STEP 无法在前端参数化生成（需 CAD 内核），接入 ezPLM 后关联真实 STEP 下载。
 */
import type { PlacedComponent } from '../../design-core/document/types';
import { padFootprintFor } from '../../design-core/geometry/footprint-pads';
import { symbolFor } from '../schematic/symbols';

const now = () => new Date().toISOString().slice(0, 10);

/** 生成 .kicad_mod 封装文件（KiCad 7 格式） */
export function buildKicadMod(c: PlacedComponent): string | null {
  const fp = padFootprintFor(c.footprint.name);
  if (!fp) return null;
  const name = c.footprint.name;
  const L: string[] = [];
  L.push(`(footprint "${name}"`);
  L.push(`  (version 20221018) (generator circuit_canvas)`);
  L.push(`  (layer "F.Cu")`);
  L.push(`  (descr "Generated by Circuit Canvas · ezPLM.cn · ${now()}")`);
  L.push(`  (attr smd)`);
  // 位号丝印
  L.push(`  (fp_text reference "REF**" (at 0 ${-(fp.bodyH / 2 + 1.5)}) (layer "F.SilkS") (effects (font (size 1 1) (thickness 0.15))))`);
  L.push(`  (fp_text value "${c.mpn}" (at 0 ${fp.bodyH / 2 + 1.5}) (layer "F.Fab") (effects (font (size 1 1) (thickness 0.15))))`);
  // 本体丝印外框
  const hw = fp.bodyW / 2, hh = fp.bodyH / 2;
  L.push(`  (fp_rect (start ${-hw} ${-hh}) (end ${hw} ${hh}) (stroke (width 0.12) (type solid)) (layer "F.SilkS"))`);
  // Courtyard
  const cw = c.footprint.geometry.courtyardWidthMm / 2, ch = c.footprint.geometry.courtyardHeightMm / 2;
  L.push(`  (fp_rect (start ${-cw} ${-ch}) (end ${cw} ${ch}) (stroke (width 0.05) (type solid)) (layer "F.CrtYd"))`);
  // 焊盘
  for (const p of fp.pads) {
    if (p.round) {
      // THT 圆孔
      const drill = Math.max(0.8, p.w - 0.6);
      L.push(`  (pad "${p.num}" thru_hole circle (at ${p.x} ${p.y}) (size ${p.w} ${p.h}) (drill ${drill.toFixed(2)}) (layers "*.Cu" "*.Mask"))`);
    } else {
      L.push(`  (pad "${p.num}" smd roundrect (at ${p.x} ${p.y}) (size ${p.w} ${p.h}) (layers "F.Cu" "F.Paste" "F.Mask") (roundrect_rratio 0.15))`);
    }
  }
  L.push(`)`);
  return L.join('\n');
}

/** 生成 .kicad_sym 符号库文件（KiCad 7 格式，简化引脚） */
export function buildKicadSym(c: PlacedComponent): string {
  const sym = symbolFor(c);
  const name = c.mpn.replace(/"/g, '');
  // 端口 → 引脚：px 坐标转 mil-ish（KiCad 符号单位 mm，栅格 2.54）；用 0.05 缩放让尺寸合理
  const S = 0.254; // 10px ≈ 2.54mm 引脚栅格
  const w = sym.w * S, h = sym.h * S;
  const L: string[] = [];
  L.push(`(kicad_symbol_lib (version 20220914) (generator circuit_canvas)`);
  L.push(`  (symbol "${name}" (in_bom yes) (on_board yes)`);
  L.push(`    (property "Reference" "${c.reference.replace(/\d+$/, '')}" (at 0 ${(h / 2 + 2).toFixed(2)} 0) (effects (font (size 1.27 1.27))))`);
  L.push(`    (property "Value" "${name}" (at 0 ${-(h / 2 + 2).toFixed(2)} 0) (effects (font (size 1.27 1.27))))`);
  L.push(`    (property "Footprint" "${c.footprint.name}" (at 0 0 0) (effects (font (size 1.27 1.27)) hide))`);
  L.push(`    (symbol "${name}_0_1"`);
  L.push(`      (rectangle (start ${(-w / 2).toFixed(2)} ${(h / 2).toFixed(2)}) (end ${(w / 2).toFixed(2)} ${(-h / 2).toFixed(2)}) (stroke (width 0.254) (type solid)) (fill (type background)))`);
  L.push(`    )`);
  L.push(`    (symbol "${name}_1_1"`);
  sym.ports.forEach((p, i) => {
    // 端口坐标（符号左上原点）→ KiCad 中心原点，Y 翻转
    const px = (p.x - sym.w / 2) * S;
    const py = (sym.h / 2 - p.y) * S;
    const angle = p.x <= 0 ? 0 : p.x >= sym.w ? 180 : p.y >= sym.h ? 90 : 270;
    L.push(`      (pin passive line (at ${(px + (angle === 0 ? -2.54 : angle === 180 ? 2.54 : 0)).toFixed(2)} ${(py + (angle === 90 ? -2.54 : angle === 270 ? 2.54 : 0)).toFixed(2)} ${angle}) (length 2.54)`);
    L.push(`        (name "${p.name ?? i + 1}" (effects (font (size 1.27 1.27)))) (number "${i + 1}" (effects (font (size 1.27 1.27)))))`);
  });
  L.push(`    )`);
  L.push(`  )`);
  L.push(`)`);
  return L.join('\n');
}

export function downloadText(text: string, filename: string) {
  const a = document.createElement('a');
  a.href = URL.createObjectURL(new Blob([text], { type: 'text/plain;charset=utf-8' }));
  a.download = filename;
  a.click();
  URL.revokeObjectURL(a.href);
}
